apiVersion: operb.example.io/v1
kind: Foo
metadata:
  name: example-foo
  namespace: operb
spec:
  chart: oci://10.88.0.1:5000/helm-charts/foo
  chartVersion: 1.0.0
  values: |
    name: hello
    another: world