apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespaceOverride }}
roleRef:
  name: {{ .Values.name }}
  kind: Role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespaceOverride }}
